### ISSUE TITLE
Feature: Support other arcitectures

### ISSUE THREAD

**Issue by daniel-wtd** [flathub/com.shatteredpixel.shatteredpixeldungeon#18]
As a user, i want to have proper support for all supported architectures from flathub to allow installations on aarch64, x86_64, etc.

Details:

Currently the pre-compiled jar from upstream is used to support x86 and x86_64. Supporting other architectures like aarch64 is recommended to allow installations on raspberries, pine devices, etc. Therefore the jar must be compiled according to the upstream documentation as described [here](https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/docs/getting-started-desktop.md).

Acceptance criteria:

- provide new com.shatteredpixel.shatteredpixeldungeon.yaml
- provide build documentation

**Comment by hfiguiere** [comment]
The above instruction don't mention the binaries that are in the jar and how to rebuild them. They are the problem.

**Comment by hfiguiere** [comment]
There is some more info there:

https://github.com/00-Evan/shattered-pixel-dungeon/issues/385

Of course having a JAR with binaries is confusing.
