### ISSUE TITLE
Fullscreen by default?

### ISSUE THREAD

**Issue by jurf** [flathub/com.shatteredpixel.shatteredpixeldungeon#2]
I know this should be done upstream, but can’t we somehow patch this to launch in fullscreen mode, or at least with different window dimensions? A portrait window just looks bad and isn’t really a good first UX.

**Comment by daniel-wtd** [comment]
This one is fixed in 0.7.5, where you can set the fullscreen mode in the options. You only need to do this once and afterwards, the game will start in fullscreen.

**Comment by jurf** [comment]
Good enough for me.
