### ISSUE TITLE
should we give it network permission?

### ISSUE THREAD

**Issue by Lonsfor** [flathub/com.shatteredpixel.shatteredpixeldungeon#26]
game has a news page that looks very empty 

![2021-02-26_19-04](https://user-images.githubusercontent.com/15758649/109360429-22812200-787f-11eb-9175-919288e200f6.png)

also it throws an ugly error in the terminal but it otherwise works fine

**Comment by daniel-wtd** [comment]
From my perspective there shouldn't be an issue to allow network connection. We may add a very small description in the changelog or so to indicate why it is needed.
