### ISSUE TITLE
app doesn't launch via flatpak on alpine

### ISSUE THREAD

**Issue by JonathanTippy** [flathub/com.shatteredpixel.shatteredpixeldungeon#41]
I have found a solution for this problem. It seems that the script that launches the .jar of the game does not start with a shebang (#!/bin/bash) and therefore on distros like alpine with ash shell, it doesn't know what shell to use. Please consider adding a shebang to the bash file which launches the game on flatpak. (Maybe this is actually a flatpak bug and there's nothing you can do about it?)

**Comment by dschier-wtd** [comment]
I have started to work on the beta, which is available in #42 

You can test out the new build via:

```sh
flatpak install --user https://dl.flathub.org/build-repo/95942/com.shatteredpixel.shatteredpixeldungeon.flatpakref
```

**Comment by dschier-wtd** [comment]
other than you used flatpak with sudo, which should be avoided, it looks like the application was installed properly.

**Comment by snek100** [comment]
The reason I used sudo is that I was getting perms issue
![Screenshot_2022-06-30_14:31:00:486](https://user-images.githubusercontent.com/54297927/176761945-a3d61826-c93a-4f6e-aaf5-664a68e29f00.png)
s
this is the list of flatpaks, not containing pixel dungeon
![Uploading Screenshot_2022-06-30_14:31:59:868.png…]()
.

**Comment by snek100** [comment]
Oh wait, "sudo flatpak list" shows the application, however sudo flatpak run is not allowed by flatpak.

**Comment by dschier-wtd** [comment]
That is quite interesting. Unfortunately, I don't have an alpine on hand right now.

O'Neill have a look. Let's see if we can hammer this out for the packaging of 1.3.0.

**Comment by dschier-wtd** [comment]
@snek100 I just installed a plain alpine in a vm, added flatpak and installed the branch via:

```
flatpak install --user https://dl.flathub.org/build-repo/97619/com.shatteredpixel.shatteredpixeldungeon.flatpakref
```

No `sudo` provided.

Afterwards, I was able to start it via

```
flatpak run --user com.shatteredpixel.shatteredpixeldungeon
```

Could you please check, if this works for you? If not, could you please run the game with:

```
flatpak run --user --verbose com.shatteredpixel.shatteredpixeldungeon
```

and provide the log output?

**Comment by dschier-wtd** [comment]
no feedback -> closed
